### ISSUE TITLE
Imported target "TIFF::TIFF" includes non-existent path C:/bld/qt6-main_1696944674905/_h_env/Library/lib/cmake/tiff/include

### ISSUE THREAD

**Issue by jschueller** [conda-forge/libtiff-feedstock#102]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

when building qt6 on windows with 4.6.0 I get this error:

```
CMake Error in qtimageformats/src/plugins/imageformats/tiff/CMakeLists.txt:
2023-10-10T13:54:39.7768892Z   Imported target "TIFF::TIFF" includes non-existent path
2023-10-10T13:54:39.7905566Z 
2023-10-10T13:54:39.9591525Z     "C:/bld/qt6-main_1696944674905/_h_env/Library/lib/cmake/tiff/include"
```

I looked at the Library/lib/cmake/tiff/TiffTargets.cmake but it looks correct:
```
# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target TIFF::tiff
add_library(TIFF::tiff SHARED IMPORTED)

set_target_properties(TIFF::tiff PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```
any idea ?

### Installed packages

```shell
libtiff 4.6
```

### Environment info

```shell
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=800840&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=6119ccbe-9301-594f-7c27-f792b80a7fcc
```

**Comment by hmaarrfk** [comment]
it seems to be including the build time path on windows. how does that typically get addressed there?

**Comment by hmaarrfk** [comment]
```
set_target_properties(TIFF::tiff PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```

^^^ Is the above line from qt or from libtiff? if it is from qt, it seems to be wrong and likely assuming vendoring of some kind

**Comment by hmaarrfk** [comment]
I'm not an expert with cmake, but is `_IMPORT_PREFIX` equivalent to ${PREFIX}, or `${PREFIX}/lib/cmake/tiff`?

**Comment by jschueller** [comment]
oh yes, that's the build path, maybe with "detect_binary_files_with_prefix: true" then
_IMPORT_PREFIX should have a value of `${PREFIX}` at the end (`%LIBRARY_PREFIX% on windows`)

**Comment by jschueller** [comment]
looks that TiffConfig.cmake is bogus

**Comment by jschueller** [comment]
https://gitlab.com/libtiff/libtiff/-/merge_requests/541

**Comment by hmaarrfk** [comment]
xid you want to make a PR here to fix it in the feedstocks?

I'm very ok fixing build related stuff when an upstream issue or merge request is created

**Comment by jschueller** [comment]
lets see what libdiff says first, I already have a simple workaround in the qt feedstock
