### ISSUE TITLE
libtiff.la: why does it define inherited_linker_flags='  -pthread'?

### ISSUE THREAD

**Issue by croth1** [conda-forge/libtiff-feedstock#12]
For some weird reasons the libtiff.la on my mac contains:

```
# Linker flags that cannot go in dependency_libs.
inherited_linker_flags='  -pthread'
```

I am not sure how it got there and doubt that it should be there.

I tested with
> libtiff        -           4.0.6            -             4  -  conda-forge

Broader context:
I am trying to prepare a libgd package. When linking libtiff, libtool reads this variable and adds it to the linker flags. Clang however does not like `-pthread` during linking, which gives a warning. Which in turn ends up in an error due to a `-Werror` flag.

**Comment by ocefpaf** [comment]
I don't have a Mac to debug this. @jakirkham if you have some spare time can you take a quick look here please?

**Comment by jakirkham** [comment]
Why are you converting all your warnings to errors with `clang`? Compared to `gcc`, `clang` is very sensitive and many codes at least generate a few warnings with `clang`. Actually was overrunning log limits on TravisCI just due to warnings when building OpenBLAS for awhile. So I wouldn't really recommend this. Could you explain a bit more why this is necessary?

**Comment by croth1** [comment]
Oh, I did not set `-Werror`. Upstream sets those by default. Patching the build system and removing `-Werror` sure is a possibility. I just wanted to find out if this is a bug in conda-forge and should be fixed here.

**Comment by ocefpaf** [comment]
BTW the default channel has the same flag in `libtiff.la`.

**Comment by jakirkham** [comment]
> Upstream sets those by default.

I see [that]( https://github.com/libgd/libgd/blob/502e4cd873c3b37b307b9f450ef827d40916c3d6/ChangeLog#L22 ).

Yeah, sorry, I'm going to point the finger at `libgd` and would suggest that you raise an issue and point out this constraint is extreme. It seems crazy to turn every warning to an error as part of deployed builds. It may make sense as part of CI to smoke out issues on there end, but to do that with deployment builds makes no sense.

FWIW there seems to be an `--enable-werror` flag in their configure file. Maybe you could try `--disable-werror`.
