### ISSUE TITLE
undefined reference to lzma 

### ISSUE THREAD

**Issue by looooo** [conda-forge/libtiff-feedstock#21]
I got this `undefined references to lzma` errors when compiling a library which needs libtiff. Same problem can be found here: https://bugs.ghostscript.com/show_bug.cgi?id=693116
Would it be possible to build without lzma?

**Comment by jakirkham** [comment]
The interest in having lzma is for dealing with compressed TIFF formats. If you are seeing that error, it probably means that you need to pass `-llzma` and possibly an appropriate `-L` along in your compiler flags. Do you have any more details about the use case? In particular system, logs, etc.?

**Comment by ocefpaf** [comment]
Closing this as stale.
