### ISSUE TITLE
libtiff built against generally incompatible version of xz

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/libtiff-feedstock#4]
So the libtiff package is built against `xz 5.2.2`.....which isn't compatible with `5.0.5`. Trying to install `5.2.2` force my *python* to change from `3.5` to `3.4`. Oh, and of course libtiff doesn't know it's not compatible with `5.0.5`, so it happily tries to install alongside it.

**Comment by ocefpaf** [comment]
I would say that Python 3.5 is build against an incompatible `libzma` :wink: 

Anyways, I don't know how to overcome https://github.com/conda-forge/staged-recipes/pull/386#issuecomment-211530003, so we either get OS X or we get Python 3.5 out.

**Comment by pelson** [comment]
Just to let you know, I've removed the build 0 and build 1 from anaconda.org/conda-forge. These were built with the overly liberal ```jpeg``` dependencies, rather than ```jpeg 9```. In some situations, this means that we don't have a build which can be used and conda rolls back to the defaults version in that case.

**Comment by ocefpaf** [comment]
@dopplershift I believe we forgot to close this as the problem no longer exists, right? If so please re-open.
