### ISSUE TITLE
Rebuild for fixed zstd on Windows

### ISSUE THREAD

**Issue by jpgill86** [conda-forge/libtiff-feedstock#44]
zstd 1.4.3 was erroneously built and released in debug mode for Windows. This was [fixed](https://github.com/conda-forge/zstd-feedstock/pull/36) with zstd 1.4.4 build 1, released earlier today.

It seems that libtiff for Windows has zstd pinned to 1.4.3. (I noticed that ``meta.yaml`` doesn't pin it explicitly, but I see that ``index.json`` in this [tar](https://anaconda.org/conda-forge/libtiff/4.1.0/download/win-64/libtiff-4.1.0-h2e92f26_0.tar.bz2) has ``zstd >=1.4.3,<1.4.4.0a0``; I'm not sure but am guessing that it's pinned automatically at build time.) Consequently, I'm encountering errors in Windows with the latest libtiff (my quest to track this down started with ``import matplotlib.pyplot as plt`` failing with a DLL import error).

**Comment by ocefpaf** [comment]
Let's create a migration for it in https://github.com/conda-forge/conda-forge-pinning-feedstock. Closing this b/c we cannot "fix it" from this feedstock.

**Comment by jpgill86** [comment]
#45 is an attempt to fix this issue, though I'm not certain it's working (see my comments in the PR). I need guidance from someone who understands libtiff better and its dependency resolution.

**Comment by jpgill86** [comment]
> 
> 
> Let's create a migration for it in https://github.com/conda-forge/conda-forge-pinning-feedstock. Closing this b/c we cannot "fix it" from this feedstock.

Ah, that makes more sense! Thanks @ocefpaf!
