### ISSUE TITLE
Most recent build causing PIL error

### ISSUE THREAD

**Issue by djhoese** [conda-forge/libtiff-feedstock#56]
Just started getting these errors in Satpy's CI after the most recent PR (#51 and #55 maybe?). I saw @hmaarrfk and @ocefpaf worked on those. Any ideas?

```
satpy/__init__.py:53: in <module>
    from satpy.writers import available_writers  # noqa
satpy/writers/__init__.py:45: in <module>
    from trollimage.xrimage import XRImage
../../../miniconda/envs/test/lib/python3.8/site-packages/trollimage/xrimage.py:40: in <module>
    from PIL import Image as PILImage
../../../miniconda/envs/test/lib/python3.8/site-packages/PIL/Image.py:69: in <module>
    from . import _imaging as core
   ImportError: dlopen(/Users/travis/miniconda/envs/test/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so, 2): Library not loaded: @rpath/libwebp.7.dylib
     Referenced from: /Users/travis/miniconda/envs/test/lib/libtiff.5.dylib
     Reason: Incompatible library version: libtiff.5.dylib requires version 9.0.0 or later, but libwebp.7.dylib provides version 8.0.0
```

https://travis-ci.org/github/pytroll/satpy/jobs/663516059#L3943-L3953

**Comment by hmaarrfk** [comment]
dam, i thought i overconstrained things.

@conda-forge/core can you please delete  `osx-64/libtiff-4.1.0-h2ae36a8_5.tar.bz2` because there seems to be some new abi incompatibility for some reason.

**Comment by hmaarrfk** [comment]
Just the OSX version is broken.

**Comment by djhoese** [comment]
> Just the OSX version is broken.

Yes! Sorry, I should have said that. The other environments seem to be working fine.

**Comment by isuruf** [comment]
https://github.com/conda-forge/cf-mark-broken

**Comment by isuruf** [comment]
Please give the information asked in the issue template.

**Comment by hmaarrfk** [comment]
ah this is new and cool!

**Comment by hmaarrfk** [comment]
sorry, but the template is blank.

**Comment by isuruf** [comment]
I meant in this issue.

**Comment by djhoese** [comment]
I'm guessing you mean me. Yeah, sorry. Tried taking some shortcuts since I assumed @hmaarrfk knew what was going on. I should follow the templates.

**Comment by isuruf** [comment]
I found the information I needed buried in the log in travis. Closing in favour of https://github.com/conda-forge/libwebp-feedstock/issues/26

**Comment by isuruf** [comment]
`libtiff` is not broken. It's only `libwebp`. We need to create a `libwebp-base` feedstock. If you are interested in getting this fixed, please send a PR to staged-recipes.

**Comment by djhoese** [comment]
> libtiff is not broken. It's only libwebp

Ah ok. I misunderstood. Thanks.
