### ISSUE TITLE
No module named 'libtiff'

### ISSUE THREAD

**Issue by GrigoriiTarasov** [conda-forge/libtiff-feedstock#60]
Issue:

Commands that was done:
> conda config --add channels conda-forge
> conda install libtiff
> python -c 'import libtiff; print(libtiff.__version__)'
'''
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'libtiff'
'''
>which python
''' 
/home/cmo1060/anaconda3/envs/tf__1_15/bin/python
'''

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
```
# packages in environment at /home/cmo1060/anaconda3/envs/tf__1_15:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu    anaconda
absl-py                   0.10.0                   py37_0    anaconda
astor                     0.8.1                    py37_0    anaconda
blas                      1.0                         mkl    anaconda
c-ares                    1.16.1               h7b6447c_0    anaconda
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cudatoolkit               10.0.130                      0    anaconda
cudnn                     7.6.5                cuda10.0_0    anaconda
cupti                     10.0.130                      0    anaconda
gast                      0.2.2                    py37_0    anaconda
google-pasta              0.2.0                      py_0    anaconda
grpcio                    1.31.0           py37hf8bcb03_0    anaconda
h5py                      2.10.0           py37hd6299e0_1    anaconda
hdf5                      1.10.6               hb1b8bf9_0    anaconda
importlib-metadata        1.7.0                    py37_0    anaconda
intel-openmp              2020.2                      254    anaconda
jpeg                      9b                   habf39ab_1    anaconda
keras                     2.3.1                         0  
keras-applications        1.0.8                      py_1    anaconda
keras-base                2.3.1                    py37_0    anaconda
keras-preprocessing       1.1.0                      py_1    anaconda
ld_impl_linux-64          2.33.1               h53a641e_7    anaconda
libedit                   3.1.20191231         h14c3975_1    anaconda
libffi                    3.3                  he6710b0_2    anaconda
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libprotobuf               3.13.0               hd408876_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.0.9                he6b73bb_1    conda-forge
lz4-c                     1.9.2                he6710b0_1    anaconda
markdown                  3.2.2                    py37_0    anaconda
mkl                       2019.4                      243    anaconda
mkl-service               2.3.0            py37he904b0f_0    anaconda
mkl_fft                   1.2.0            py37h23d657b_0    anaconda
mkl_random                1.1.0            py37hd6b4f25_0    anaconda
ncurses                   6.2                  he6710b0_1    anaconda
numpy                     1.19.1           py37hbc911f0_0    anaconda
numpy-base                1.19.1           py37hfa32c7d_0    anaconda
openssl                   1.1.1g               h516909a_1    conda-forge
opt_einsum                3.1.0                      py_0    anaconda
pip                       20.2.2                   py37_0    anaconda
protobuf                  3.13.0           py37hf484d3e_0    anaconda
python                    3.7.9                h7579374_0  
python_abi                3.7                     1_cp37m    conda-forge
pyyaml                    5.3.1            py37h7b6447c_1    anaconda
readline                  8.0                  h7b6447c_0    anaconda
scipy                     1.5.2            py37h0b6359f_0    anaconda
setuptools                49.6.0                   py37_0    anaconda
six                       1.15.0                     py_0    anaconda
sqlite                    3.33.0               h62c20be_0    anaconda
tensorboard               1.15.0             pyhb230dea_0    anaconda
tensorflow                1.15.0          gpu_py37h0f0df58_0    anaconda
tensorflow-base           1.15.0          gpu_py37h9dcbed7_0    anaconda
tensorflow-estimator      1.15.1             pyh2649769_0    anaconda
tensorflow-gpu            1.15.0               h0d30ee6_0  
termcolor                 1.1.0                    py37_1    anaconda
tk                        8.6.10               hbc83047_0    anaconda
webencodings              0.5.1                    py37_1    anaconda
werkzeug                  0.16.1                     py_0    anaconda
wheel                     0.35.1                     py_0    anaconda
wrapt                     1.12.1           py37h7b6447c_1    anaconda
xz                        5.2.5                h7b6447c_0    anaconda
yaml                      0.2.5                h7b6447c_0    anaconda
zipp                      3.1.0                      py_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.4.4                h0b5b093_3    anaconda
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
# packages in environment at /home/cmo1060/anaconda3/envs/tf__1_15:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu    anaconda
absl-py                   0.10.0                   py37_0    anaconda
astor                     0.8.1                    py37_0    anaconda
blas                      1.0                         mkl    anaconda
c-ares                    1.16.1               h7b6447c_0    anaconda
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cudatoolkit               10.0.130                      0    anaconda
cudnn                     7.6.5                cuda10.0_0    anaconda
cupti                     10.0.130                      0    anaconda
gast                      0.2.2                    py37_0    anaconda
google-pasta              0.2.0                      py_0    anaconda
grpcio                    1.31.0           py37hf8bcb03_0    anaconda
h5py                      2.10.0           py37hd6299e0_1    anaconda
hdf5                      1.10.6               hb1b8bf9_0    anaconda
importlib-metadata        1.7.0                    py37_0    anaconda
intel-openmp              2020.2                      254    anaconda
jpeg                      9b                   habf39ab_1    anaconda
keras                     2.3.1                         0  
keras-applications        1.0.8                      py_1    anaconda
keras-base                2.3.1                    py37_0    anaconda
keras-preprocessing       1.1.0                      py_1    anaconda
ld_impl_linux-64          2.33.1               h53a641e_7    anaconda
libedit                   3.1.20191231         h14c3975_1    anaconda
libffi                    3.3                  he6710b0_2    anaconda
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libprotobuf               3.13.0               hd408876_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.0.9                he6b73bb_1    conda-forge
lz4-c                     1.9.2                he6710b0_1    anaconda
markdown                  3.2.2                    py37_0    anaconda
mkl                       2019.4                      243    anaconda
mkl-service               2.3.0            py37he904b0f_0    anaconda
mkl_fft                   1.2.0            py37h23d657b_0    anaconda
mkl_random                1.1.0            py37hd6b4f25_0    anaconda
ncurses                   6.2                  he6710b0_1    anaconda
numpy                     1.19.1           py37hbc911f0_0    anaconda
numpy-base                1.19.1           py37hfa32c7d_0    anaconda
openssl                   1.1.1g               h516909a_1    conda-forge
opt_einsum                3.1.0                      py_0    anaconda
pip                       20.2.2                   py37_0    anaconda
protobuf                  3.13.0           py37hf484d3e_0    anaconda
python                    3.7.9                h7579374_0  
python_abi                3.7                     1_cp37m    conda-forge
pyyaml                    5.3.1            py37h7b6447c_1    anaconda
readline                  8.0                  h7b6447c_0    anaconda
scipy                     1.5.2            py37h0b6359f_0    anaconda
setuptools                49.6.0                   py37_0    anaconda
six                       1.15.0                     py_0    anaconda
sqlite                    3.33.0               h62c20be_0    anaconda
tensorboard               1.15.0             pyhb230dea_0    anaconda
tensorflow                1.15.0          gpu_py37h0f0df58_0    anaconda
tensorflow-base           1.15.0          gpu_py37h9dcbed7_0    anaconda
tensorflow-estimator      1.15.1             pyh2649769_0    anaconda
tensorflow-gpu            1.15.0               h0d30ee6_0  
termcolor                 1.1.0                    py37_1    anaconda
tk                        8.6.10               hbc83047_0    anaconda
webencodings              0.5.1                    py37_1    anaconda
werkzeug                  0.16.1                     py_0    anaconda
wheel                     0.35.1                     py_0    anaconda
wrapt                     1.12.1           py37h7b6447c_1    anaconda
xz                        5.2.5                h7b6447c_0    anaconda
yaml                      0.2.5                h7b6447c_0    anaconda
zipp                      3.1.0                      py_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.4.4                h0b5b093_3    anaconda

</details>

Instalation output after
> conda install libtiff

<details>
```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/cmo1060/anaconda3/envs/tf__1_15

  added / updated specs:
    - libtiff


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libtiff-4.0.9              |       he6b73bb_1         521 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         521 KB

The following NEW packages will be INSTALLED:

  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m

The following packages will be UPDATED:

  openssl               anaconda::openssl-1.1.1g-h7b6447c_0 --> conda-forge::openssl-1.1.1g-h516909a_1

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates     anaconda::ca-certificates-2020.7.22-0 --> conda-forge::ca-certificates-2020.6.20-hecda079_0
  certifi                anaconda::certifi-2020.6.20-py37_0 --> conda-forge::certifi-2020.6.20-py37hc8dfbb8_0
  libtiff                anaconda::libtiff-4.1.0-h2733197_1 --> conda-forge::libtiff-4.0.9-he6b73bb_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
libtiff-4.0.9        | 521 KB    | ##################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
</details>

**Comment by jakirkham** [comment]
Just to note, this is the C library and doesn't contain any bindings to it (Python or otherwise). Would suggest looking at `tifffile` if a Python TIFF reading library is what you are looking for.
