### ISSUE TITLE
[4.3.0->4.4.0 ABI breakage?] undefined symbol: _TIFFDataSize

### ISSUE THREAD

**Issue by inducer** [conda-forge/libtiff-feedstock#78]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Two CI jobs:

- [Working](https://gitlab.tiker.net/inducer/pytential/-/jobs/411824)
- [Failed](https://gitlab.tiker.net/inducer/pytential/-/jobs/416349)

Symptom:
```
Traceback (most recent call last):
  File "/var/lib/gitlab-runner/builds/VFPjm48d/3/inducer/pytential/.miniforge3/envs/testing/lib/python3.10/site-packages/pytools/prefork.py", line 51, in call_capture_output
    raise ExecError("status {} invoking '{}': {}".format(
pytools.prefork.ExecError: status 127 invoking 'gmsh -version': gmsh: symbol lookup error: /var/lib/gitlab-runner/builds/VFPjm48d/3/inducer/pytential/.miniforge3/envs/testing/bin/../lib/./././libfreeimage.so.3: undefined symbol: _TIFFDataSize
```
Between those two, libtiff went from 4.3.0 to 4.4.0.

Or maybe this is https://github.com/conda-forge/freeimage-feedstock/issues depending on a symbol on which it shouldn't? Not sure.

### Installed packages

```shell
(see above CI logs)
```

### Environment info

```shell
(see above CI logs)
```

**Comment by hmaarrfk** [comment]
I think libtiff removed an internal function:
https://gitlab.com/libtiff/libtiff/-/commit/11f3f279608ae9e68f014717393197f430f9be58

**Comment by hmaarrfk** [comment]
Can you adapt the PR https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/272 for your package?

**Comment by hmaarrfk** [comment]
oh freeimage points to it it seems.

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/freeimage-feedstock/pull/32

**Comment by hmaarrfk** [comment]
i just released a new freeimage, and I think I fixed the mentionned issue. Find build number 9.

I'm trying to patch the repo, but I don't like doing that too much since it is somwhat dangerous. I like to leave it open for a few days.

**Comment by hmaarrfk** [comment]
Pretty confident this is fixed. Reopen if it isn't
