### ISSUE TITLE
libtiff 4.4 pkg-config file broken on Windows / Switch to libjpeg-turbo?

### ISSUE THREAD

**Issue by pkgw** [conda-forge/libtiff-feedstock#80]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

As seen in conda-forge/librsvg-feedstock#96, version 4.4 of libtiff adds a new `Requires.private:` line to its pkg-config file that breaks downstream libraries on Windows: the new libtiff version requires `libjpeg.pc` as a dependency, but conda-forge's Windows build of `jpeg` doesn't provide a pkg-config file. The non-Windows builds do, so it's not a problem elsewhere.

A potential solution would be to switch this library from depending on `jpeg` on Windows to `libjpeg-turbo`, which *does* provide a `libjpeg.pc` on all platforms. I *think* that this is pretty much a drop-in change, but I don't feel like I fully understand the ABI/etc implications of switching. Thoughts?

(Alternatively, we could update the `jpeg` CMake file to build and install the `.pc` file. The CMake file is custom to conda-forge.

CC @conda-forge/jpeg and @conda-forge/libjpeg-turbo for visibility.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by hmaarrfk** [comment]
The switch to jpeg turbo is a sticky issue: https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/348

I think for now, we should add the missing `.pc` to jpeg on windows.

**Comment by hmaarrfk** [comment]
(With the desire to move to jpeg turbo, we should add it both the 9 branch and the 8 branch of jpeg the jpeg-feedstock repo.)

**Comment by pkgw** [comment]
Thanks for the additional context; that's kind of what I suspected. I think it shouldn't be too hard to set up the `.pc` in `jpeg`, if I can find the time to sit down for an hour, so that's what I'll aim to do unless the libjpeg-turbo situation magically unsticks itself.

**Comment by pkgw** [comment]
OK, the two pull requests autolinked above make the libtiff pkg-config file valid again and allow me to build `librsvg` on my test machine.

**Comment by hmaarrfk** [comment]
That you so much for improving the ecosystem!
