### ISSUE TITLE
Unexpected SONAME for v4.5.0

### ISSUE THREAD

**Issue by sdebionne** [conda-forge/libtiff-feedstock#88]
### Comment:

It's not clear to me how versioning works with libtiff but, since the release of 4.5.0, our packages (linked with 4.4.0, aka `libtiff.so.5`) are broken since 4.5.0 installs `libtiff.so.6`.

For a *minor* version increment, SONAME *major* version was incremented in:
https://gitlab.com/libtiff/libtiff/-/commit/dc73ae317e8ea3407bc15f8adfc8d9faa909b6f3

Actually it looks like the SONAME does not follow the version.

I guess we could pin libtiff but IMHO, SONAME and version should match and versions should follow SemVer in Conda. Shall the build system be patched?

**Comment by hmaarrfk** [comment]
I believe i patched the metadata for conda-forge.

This is a problem that has happened quite often with ABI breakages with minor version:
https://github.com/conda-forge/libtiff-feedstock/issues/77

Can you provide information about your environment? I thought i caught all the packages at conda-forge to avoid this.
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/375

**Comment by sdebionne** [comment]
Our packages are not built on conda-forge. Now I see that you have taken some disposition to workaround the issue. I guess we will have to pin with `< 4.5` as you did with the repodata patch.

**Comment by hmaarrfk** [comment]
Let me know if you need anything else.
